---
motd: '&r&l&bTriton MC&r'
camp.timer: 30
amethyst.motion: 2
feather.motion: 2
koth.webhook: ""
admin.webhook: "https://discord.com/api/webhooks/1408152866266546277/Po4z04Lyks_8hNBL-YjMlg9KfoOFTCq07Mcm7gaKRnkJWnf1trhbckvtlIA0ZnPWnC2K"
raid.webhook: "https://discord.com/api/webhooks/1427438782415765596/kv3WcmjnK8N2bdjstCOw3PGhvkefUhHEqQ5oja1eb8jjNZwu3bU4FIUMSzqJigUjrTgS"
faction.max.members: 7
facion.regeneration.offline: true
scoreboard.title:
- "&l&3            &r"
- "&l&3T&r"
- "&l&3TR&r"
- "&l&3TRI&r"
- "&l&3TRIT&r"
- "&l&3TRITO&r"
- "&l&3TRITON&r"
- "&l&3TRITON &7M&r"
- "&l&3TRITON &7MA&r"
- "&l&3TRITON &7MAP&r"
- "&l&3TRITON &7MAP &32&r"
- "&l&bTRITON &7MAP 2&r"
- "&l&bRITON &7MAP 2&r"
- "&l&bITON &7MAP 2&r"
- "&l&bTON &7MAP 2&r"
- "&l&bON &7MAP 2&r"
- "&l&bN &7MAP 2&r"
- "&l&b  &7MAP 2&r"
- "&l&b        &r"
scoreboard.placeholder: ''

# Mensajes
join.message: '§6[§a+§6] §f{player} §a se unió al servidor'
quit.message: '§6[§c-§6] §f{player} §c salió del servidor'

# Keyall
Keyall:
  Angel: 5
  Blessed: 15
  Fall: 25
  Rare: 35
  Items: 40
  Starter: 45

# Keyall OP
KeyallOP:
  Evil: 10
  Angel: 30
  Blessed: 35
  Fall: 40
  Rare: 45
  Items: 55
  Starter: 64
